# Site settings
title: Waylay blog
email: info@waylay.io
description: > # this means to ignore newlines until "baseurl:"
  Waylay is a visual tool for automating IoT solutions. It connects devices and
  applications to enable better real-time decisions via smart reasoning.
baseurl: "/blog/engineering" # the subpath of your site, e.g. /blog/
url: "http://blog.waylay.io" # the base hostname & protocol for your site
twitter_username: waylay_io
github_username:  waylayio

# Build settings
markdown: kramdown
