FROM docker.waylay.io:5000/waylay/docs
MAINTAINER Gilles De Mey <gilles@waylay.io>

ADD index.md docs/index.md
ADD projects/hoard/docs/ docs/hoard/
ADD projects/device-gateway/docs/ docs/device-gateway/
